// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmyttSMeya7vhjoqOo6RGP4c-vIqHgDQE',
    appId: '1:192674429185:web:f6023aa263669cedc9c300',
    messagingSenderId: '192674429185',
    projectId: 'aquemarropa2-f91c8',
    authDomain: 'aquemarropa2-f91c8.firebaseapp.com',
    storageBucket: 'aquemarropa2-f91c8.appspot.com',
    measurementId: 'G-MVDRRQ3ZN8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiAeVxYn6M6UnzaFYx-bQ9dv6tsymsofE',
    appId: '1:192674429185:android:d90b94da618bb3d5c9c300',
    messagingSenderId: '192674429185',
    projectId: 'aquemarropa2-f91c8',
    storageBucket: 'aquemarropa2-f91c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdhYoeNVVgesVfLMSMfxDx9q2WcsR094I',
    appId: '1:192674429185:ios:57cf4c39ab982493c9c300',
    messagingSenderId: '192674429185',
    projectId: 'aquemarropa2-f91c8',
    storageBucket: 'aquemarropa2-f91c8.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdhYoeNVVgesVfLMSMfxDx9q2WcsR094I',
    appId: '1:192674429185:ios:57cf4c39ab982493c9c300',
    messagingSenderId: '192674429185',
    projectId: 'aquemarropa2-f91c8',
    storageBucket: 'aquemarropa2-f91c8.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmyttSMeya7vhjoqOo6RGP4c-vIqHgDQE',
    appId: '1:192674429185:web:10a20b14be4d0c54c9c300',
    messagingSenderId: '192674429185',
    projectId: 'aquemarropa2-f91c8',
    authDomain: 'aquemarropa2-f91c8.firebaseapp.com',
    storageBucket: 'aquemarropa2-f91c8.appspot.com',
    measurementId: 'G-2YYSYYK9HK',
  );
}
